routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/ 

    Auth::routes();

    Route::get('/user/verify/{token}', 'Auth\RegisterController@verifyUser');

    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    
    Route::get('password/reset/{token?}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');

    Route::get('/logout', 'Auth\LoginController@logout')->name('logout' );

    Route::get('login/resend', 'Auth\ActivationResendController@verificationMail')->name('login.verify');

    Route::post('resend', 'Auth\ActivationResendController@resend')->name('login.resend');

    Route::get('about', 'PagesController@getAbout');

    Route::get('contact', 'PagesController@getContact');

    Route::post('contact', 'PagesController@postContact');

    Route::get('/', 'PagesController@getIndex')->middleware('auth');

    Route::resource('questions', 'PostController');

    Route::get('questions/categories/homework', 'PostController@getHomework')->name('categories.homework');

    Route::get('questions/categories/programming', 'PostController@getProgramming')->name('categories.programming');

    Route::get('questions/categories/lecture', 'PostController@getLecture')->name('categories.lecture');
    
    Route::get('profile', 'UserController@getProfile')->name('account.profile');
    
    Route::post('profile', 'UserController@getPicture')->name('profile.update');

    Route::get('user/{id}', 'UserController@getUser')->name('account.user');

    Route::post('user/{id}/update', 'UserController@updateUser')->name('account.update');

    Route::delete('user/{id}/destroy', 'UserController@destroy')->name('account.destroy');

    Route::get('users', 'UserController@getUsers')->name('account.users');
    
    Route::post('profile', 'UserController@update')->name('profile.update');

    Route::get('profile/{id}', 'UserController@show')->name('account.show');

    Route::get('archive', 'FolderController@getPage')->name('folders.page')->middleware('lecturer');
    
    Route::get('archive/course/{folder_id}', 'FolderController@show')->name('folders.show')->middleware('lecturer');

    Route::get('archive/{program_id}', 'FolderController@index')->name('folders.index')->middleware('lecturer');

    Route::get('archive/course/{program_id}/create', 'FolderController@create')->name('folders.create')->middleware('lecturer');
    
    Route::get('archive/course/{folder_id}/edit', 'FolderController@edit')->name('folders.edit')->middleware('lecturer');
    
    Route::post('folders/{program_id}', 'FolderController@store')->name('folders.store')->middleware('lecturer');

    Route::post('archive/course/{folder_id}', 'FolderController@update')->name('folders.update')->middleware('lecturer');

    Route::delete('archive/course/{folder_id}', 'FolderController@destroy')->name('folders.destroy')->middleware('lecturer');
    
    Route::delete('archive/course/folder/{file_id}', 'FilesController@destroy')->name('files.destroy')->middleware('lecturer');
    
    Route::post('files/{folder_id}', 'FilesController@store')->name('files.store')->middleware('lecturer');

    Route::get('archive/course/folder/{file_id}', 'FilesController@show')->name('files.show')->middleware('lecturer');

    Route::get('archive/course/{folder_id}/files/create', 'FilesController@create')->name('files.create')->middleware('lecturer');

    Route::get('archive/course/folder/{file_id}/edit', 'FilesController@edit')->name('files.edit')->middleware('lecturer');
    
    Route::post('archive/course/folder/{file_id}', 'FilesController@update')->name('files.update')->middleware('lecturer');
    
    Route::post('comments/{post_id}', ['uses' => 'CommentsController@store', 'as' => 'comments.store']);
    
    Route::put('comments/{id}', ['uses' => 'CommentsController@update', 'as' => 'comments.update']);

    Route::get('comments/{id}/edit', ['uses' => 'CommentsController@edit', 'as' => 'comments.edit']);

    Route::delete('comments/{id}', ['uses' => 'CommentsController@destroy', 'as' => 'comments.destroy']);

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Post;

class Category extends Model
{
    protected $table = 'categories';

    public function questions()
    {
        return $this->hasMany('App\Post');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use App\Post;

class CategoryController extends Controller
{
    public function __construct() {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        $questions = Post::all();

        return view('categories\index')->withCategories($categories)->withQuestions($questions);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/categories/homework.blade.php
@extends('layouts/main')

@section('title', '- Homework')

@section('styles')

    {{Html::style('css/styles.css')}}
    
@endsection

@section('content')

    <div class="input-container input-container-posts">
        <div class="row">
            <div class="col-md-8 col-sm-8 col-8">
                <h1 class="all-form-group">Homework</h1>
            </div>
            <div class="col-md-4 col-sm-4 col-4 top-button">
                <a href="{{route('questions.create')}}" class="submit-button posts-ask-question-button">Ask question</a>
            </div>
            <div class="col-md-12">
                <hr class="create-hr-upper">
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 mx-auto">
                <div class="text-center category-box">
                    <a href="{{route('categories.homework')}}" class="all-form-group categories-button">Homework</a><br>
                </div>
            </div>
            <div class="col-md-4 mx-auto">
                <div class="text-center category-box">              
                    <a href="{{route('categories.programming')}}" class="all-form-group categories-button">Programming</a><br>
                </div>
            </div>
            <div class="col-md-4 mx-auto">
                <div class="text-center category-box">
                    <a href="{{route('categories.lecture')}}" class="all-form-group categories-button">Lecture</a><br>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <table class="table all-form-group">
                    <thead class="thead-styling">
                        <th>title</th>
                        <th>description</th>
                        <th class="table-category">comments</th>
                        <th class="table-time">last modified</th>
                        <th></th>
                    </thead>

                    <tbody>
                        @foreach ($posts->where('category_id', '1') as $post)
                            <tr>
                                <td class="table-styling">{{$post->title}}</td>
                                <td class="table-styling">{{substr($post->body, 0, 10)}} {{strlen($post -> body) > 50 ? "..." : ""}}</td>
                                <td class="table-styling table-category">{{$post->comments->count()}}</td>
                                <td style="text-transform: lowercase; table-styling" class="table-time">{{date('M j, Y', strtotime($post -> updated_at))}}</td>
                                <td>
                                    <a href="{{route('questions.show', $post -> id)}}" class="submit-button html-button">View</a>
                                    @if((Auth::user()->id == $post->user->id) || (Auth::user()->isAdmin == 1))
                                    <a href="{{route('questions.edit', $post -> id)}}" class="submit-button html-button html-button-left">Edit</a>
                                    @endif
                                </td>
                            </tr>  
                        @endforeach
                    </tbody>
                </table>
                <div class="pagination">
                    {{$posts -> links("pagination::bootstrap-4"), ['class' => 'pagination']}}
                </div>
            </div>
        </div>
    </div>

@endsection

@section('scripts')

    {{Html::script('js/parsley.min.js')}}

@endsection

resources/views/categories/lecture.blade.php
@extends('layouts/main')

@section('title', '- Lecture')

@section('styles')

    {{Html::style('css/styles.css')}}
    
@endsection

@section('content')

    <div class="input-container input-container-posts">
        <div class="row">
            <div class="col-md-8 col-sm-8 col-8">
                <h1 class="all-form-group">Lecture</h1>
            </div>
            <div class="col-md-4 col-sm-4 col-4 top-button">
                <a href="{{route('questions.create')}}" class="submit-button posts-ask-question-button">Ask question</a>
            </div>
            <div class="col-md-12">
                <hr class="create-hr-upper">
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 mx-auto">
                <div class="text-center category-box">
                    <a href="{{route('categories.homework')}}" class="all-form-group categories-button">Homework</a><br>
                </div>
            </div>
            <div class="col-md-4 mx-auto">
                <div class="text-center category-box">              
                    <a href="{{route('categories.programming')}}" class="all-form-group categories-button">Programming</a><br>
                </div>
            </div>
            <div class="col-md-4 mx-auto">
                <div class="text-center category-box">
                    <a href="{{route('categories.lecture')}}" class="all-form-group categories-button">Lecture</a><br>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <table class="table all-form-group">
                    <thead class="thead-styling">
                        <th>title</th>
                        <th>description</th>
                        <th class="table-category">comments</th>
                        <th class="table-time">last modified</th>
                        <th></th>
                    </thead>

                    <tbody>
                        @foreach ($posts->where('category_id', '3') as $post)
                            <tr>
                                <td class="table-styling">{{$post->title}}</td>
                                <td class="table-styling">{{substr($post->body, 0, 10)}} {{strlen($post -> body) > 50 ? "..." : ""}}</td>
                                <td class="table-styling table-category">{{$post->comments->count()}}</td>
                                <td class="table-time" style="text-transform: lowercase; table-styling">{{date('M j, Y', strtotime($post -> updated_at))}}</td>
                                <td>
                                    <a href="{{route('questions.show', $post -> id)}}" class="submit-button html-button">View</a>
                                    @if((Auth::user()->id == $post->user->id) || (Auth::user()->isAdmin == 1))
                                    <a href="{{route('questions.edit', $post -> id)}}" class="submit-button html-button html-button-left">Edit</a>
                                    @endif
                                </td>
                            </tr>  
                        @endforeach
                    </tbody>
                </table>
                <div class="pagination">
                    {{$posts -> links("pagination::bootstrap-4"), ['class' => 'pagination']}}
                </div>
            </div>
        </div>
    </div>

@endsection

@section('scripts')

    {{Html::script('js/parsley.min.js')}}

@endsection

resources/views/categories/programming.blade.php
@extends('layouts/main')

@section('title', '- Programming')

@section('styles')

    {{Html::style('css/styles.css')}}
    
@endsection

@section('content')

    <div class="input-container input-container-posts">
        <div class="row">
            <div class="col-md-8 col-sm-8 col-8">
                <h1 class="all-form-group">Programming</h1>
            </div>
            <div class="col-md-4 col-sm-4 col-4 top-button">
                <a href="{{route('questions.create')}}" class="submit-button posts-ask-question-button">Ask question</a>
            </div>
            <div class="col-md-12">
                <hr class="create-hr-upper">
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 mx-auto">
                <div class="text-center category-box">
                    <a href="{{route('categories.homework')}}" class="all-form-group categories-button">Homework</a><br>
                </div>
            </div>
            <div class="col-md-4 mx-auto">
                <div class="text-center category-box">              
                    <a href="{{route('categories.programming')}}" class="all-form-group categories-button">Programming</a><br>
                </div>
            </div>
            <div class="col-md-4 mx-auto">
                <div class="text-center category-box">
                    <a href="{{route('categories.lecture')}}" class="all-form-group categories-button">Lecture</a><br>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <table class="table all-form-group">
                    <thead class="thead-styling">
                        <th>title</th>
                        <th>description</th>
                        <th class="table-category">comments</th>
                        <th class="table-time">last modified</th>
                        <th></th>
                    </thead>

                    <tbody>
                        @foreach ($posts->where('category_id', '2') as $post)
                            <tr>
                                <td class="table-styling">{{$post->title}}</td>
                                <td class="table-styling">{{substr($post->body, 0, 10)}} {{strlen($post -> body) > 50 ? "..." : ""}}</td>
                                <td class="table-styling table-category">{{$post->comments->count()}}</td>
                                <td class="table-time" style="text-transform: lowercase; table-styling">{{date('M j, Y', strtotime($post -> updated_at))}}</td>
                                <td>
                                    <a href="{{route('questions.show', $post -> id)}}" class="submit-button html-button">View</a>
                                    @if((Auth::user()->id == $post->user->id) || (Auth::user()->isAdmin == 1))
                                    <a href="{{route('questions.edit', $post -> id)}}" class="submit-button html-button html-button-left">Edit</a>
                                    @endif
                                </td>
                            </tr>  
                        @endforeach
                    </tbody>
                </table>
                <div class="pagination">
                    {{$posts -> links("pagination::bootstrap-4"), ['class' => 'pagination']}}
                </div>
            </div>
        </div>
    </div>

@endsection

@section('scripts')

    {{Html::script('js/parsley.min.js')}}

@endsection